version: "3.9"

services:
  database:
    image: postgres:15.2
    restart: always
    container_name: integration-test-prisma
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests

